version: '{branch}-{build}'
build: off
image:
- Visual Studio 2019
environment:
  global:
    WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'
  matrix:
    - TOXENV: '3.6-buildonly-nocover'
      TOXPYTHON: C:\python36\python.exe
      PYTHON_HOME: C:\python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    - TOXENV: '3.6-buildonly-nocover'
      TOXPYTHON: C:\python36-x64\python.exe
      PYTHON_HOME: C:\python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
    - TOXENV: '3.7-buildonly-nocover'
      TOXPYTHON: C:\python37\python.exe
      PYTHON_HOME: C:\python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
    - TOXENV: '3.7-buildonly-nocover'
      TOXPYTHON: C:\python37-x64\python.exe
      PYTHON_HOME: C:\python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
    - TOXENV: '3.8-buildonly-nocover'
      TOXPYTHON: C:\python38\python.exe
      PYTHON_HOME: C:\python38
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '32'
    - TOXENV: '3.8-buildonly-nocover'
      TOXPYTHON: C:\python38-x64\python.exe
      PYTHON_HOME: C:\python38-x64
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '64'
    - TOXENV: '3.9-buildonly-nocover'
      TOXPYTHON: C:\python39\python.exe
      PYTHON_HOME: C:\python39
      PYTHON_VERSION: '3.9'
      PYTHON_ARCH: '32'
    - TOXENV: '3.9-buildonly-nocover'
      TOXPYTHON: C:\python39-x64\python.exe
      PYTHON_HOME: C:\python39-x64
      PYTHON_VERSION: '3.9'
      PYTHON_ARCH: '64'
    - TOXENV: check
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
    - TOXENV: '3.6-nocover'
      TOXPYTHON: C:\python36\python.exe
      PYTHON_HOME: C:\python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    - TOXENV: '3.6-nocover'
      TOXPYTHON: C:\python36-x64\python.exe
      PYTHON_HOME: C:\python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
    - TOXENV: '3.7-nocover'
      TOXPYTHON: C:\python37\python.exe
      PYTHON_HOME: C:\python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
    - TOXENV: '3.7-nocover'
      TOXPYTHON: C:\python37-x64\python.exe
      PYTHON_HOME: C:\python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
    - TOXENV: '3.8-nocover'
      TOXPYTHON: C:\python38\python.exe
      PYTHON_HOME: C:\python38
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '32'
    - TOXENV: '3.8-nocover'
      TOXPYTHON: C:\python38-x64\python.exe
      PYTHON_HOME: C:\python38-x64
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '64'
    - TOXENV: '3.9-nocover'
      TOXPYTHON: C:\python39\python.exe
      PYTHON_HOME: C:\python39
      PYTHON_VERSION: '3.9'
      PYTHON_ARCH: '32'
    - TOXENV: '3.9-nocover'
      TOXPYTHON: C:\python39-x64\python.exe
      PYTHON_HOME: C:\python39-x64
      PYTHON_VERSION: '3.9'
      PYTHON_ARCH: '64'
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - python -u ci\appveyor-bootstrap.py
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - '%WITH_COMPILER% %PYTHON_HOME%\Scripts\tox'

after_test:
### if tagged commit, build/upload wheel
#  - IF "%TOXENV%"=="2.7-buildonly-nocover" IF "%PYTHON_ARCH%"=="32" (%WITH_COMPILER% %TOXPYTHON% setup.py sdist)
### Twine commands not working, remove for now
#  - IF "%APPVEYOR_REPO_TAG%"=="true" IF NOT "%TOXENV%"=="%TOXENV:buildonly=%" (
#      %WITH_COMPILER% %TOXPYTHON% setup.py bdist_wheel &&
#      %PYTHON_HOME%\Scripts\pip install twine &&
#      %PYTHON_HOME%\Scripts\twine upload -u %PYPI_USER% -p %PYPI_PASS% dist/*
#    )

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
artifacts:
  - path: dist\*
### To enable remote debugging uncomment this:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/main/scripts/enable-rdp.ps1'))

