language: python
python:
{% for env, config in tox_environments|dictsort %}{% if not config.cover %}
  - "{{ config.python[-3:] }}"
{% endif %}{% endfor %}
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install numpy tox-travis coveralls
  - python setup.py install
script:
  - |
    if [ $TRAVIS_PYTHON_VERSION == "3.7" ]; then
        tox -e check,docs
    fi
  - tox -e $TRAVIS_PYTHON_VERSION
after_success:
  - coveralls --rcfile=setup.cfg
notifications:
  email:
    on_success: never
    on_failure: always